version: '3.8'

services:
  cineverse-db:
    image: mysql:8.0
    container_name: cineverse_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cineverse123
      MYSQL_DATABASE: cineverse_db
      MYSQL_USER: cineverse_user
      MYSQL_PASSWORD: cineverse_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cineverse_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: cineverse-db
      PMA_USER: root
      PMA_PASSWORD: cineverse123
    depends_on:
      - cineverse-db

volumes:
  mysql_data: